[project]
name = "a-maze-ing"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
    "common",
    "graphics",
    "mazegen",
    "mlx",
]

[project.scripts]
a-maze-ing = "a_maze_ing.main:main"

[tool.uv.sources]
common = { workspace = true }
graphics = { workspace = true }
mazegen = { workspace = true }
mlx = { workspace = true }

[tool.uv.workspace]
members = [
    "libs/common",
    "libs/graphics",
    "libs/mazegen",
    "libs/mlx/python"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "flake8-pyproject>=1.2.4",
    "flake8-docstrings>=1.7.0",   
    "mypy>=2.0.0",
]

[tool.mypy]
warn_return_any = true
warn_unused_ignores = true
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true
exclude= "libs/mlx"

[tool.flake8]
exclude  = ".git, __pycache__, build, dist, libs/mlx, .venv"
extend-ignore = "E203, D401"
